// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXxN9-VQrQ9x-WpDfUfnm9Oxn88zS7y8',
    appId: '1:356140900885:web:e24a5e87b1d58bb7c4e41c',
    messagingSenderId: '356140900885',
    projectId: 'driverapp-3507a',
    authDomain: 'driverapp-3507a.firebaseapp.com',
    storageBucket: 'driverapp-3507a.appspot.com',
    measurementId: 'G-Q91DH1K83E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcj8efe6W2MrH4vgytcdCL9eUw8iuJicc',
    appId: '1:356140900885:android:4ee76c7d8639f961c4e41c',
    messagingSenderId: '356140900885',
    projectId: 'driverapp-3507a',
    storageBucket: 'driverapp-3507a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNCB7-_dTE_36i41TJBNlA5HhtO8BbRA',
    appId: '1:356140900885:ios:c4681d94fd9656f3c4e41c',
    messagingSenderId: '356140900885',
    projectId: 'driverapp-3507a',
    storageBucket: 'driverapp-3507a.appspot.com',
    iosClientId: '356140900885-ujq667slevo675sid42gc8cghdhd1feu.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );
}
